apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-nginx
  namespace: app01

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vulnerable-nginx

  template:
    metadata:
      labels:
        app: vulnerable-nginx

    spec:
      containers:
      - name: nginx

        image: nginx:1.16

        ports:
        - containerPort: 80

        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"