apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-password-secret
  namespace: app01

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore

  target:
    name: db-secret

  data:
  - secretKey: password
    remoteRef:
      key: db-password