apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
  namespace: app01

spec:
  containers:
  - name: demo
    image: busybox
    command: ["sleep", "3600"]

    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"

    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username

    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password